# I want to use default settings of Nginx so I'm leaving events{} empty
events {}

# i want to start the nginx
http {
  server {
    # Then I'll start listening on port 80
    listen 80;
    # Specifies the domain this is applicable to
    server_name heyvarchas.duckdns.org;
    # Redirecting to Https
    return 301 https://$host$request_uri;
  }

  # Another server 
  server {
    # Listening on 443 (gtk it's the standard port) and use ssl for TLS encryption
    listen 443 ssl;
    server_name heyvarchas.duckdns.org;

    # Now I'm giving the path to the SSL
    ssl_certificate /etc/letsencrypt/live/heyvarchas.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/heyvarchas.duckdns.org/privkey.pem;

    # Now I'm going to focus on the API backend routing
    location /api/ {
      proxy_pass http://backend:3000;
    }

    # This is the frontend routing part
    location / {
      proxy_pass http://frontend:80;
    }
  }
}